# Define o backend (app) e o banco PostgreSQL.

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caminhofacil_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - caminhofacil_net
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: caminhofacil_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-caminhofacil}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-caminhofacil}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - caminhofacil_net
    restart: unless-stopped

volumes:
  pgdata:

networks:
  caminhofacil_net:
    external: true
